apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "ibmcloud-object-storage-plugin"
  namespace: kube-system
  labels:
    app: "ibmcloud-object-storage-plugin"
    release: "v001"
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: "ibmcloud-object-storage-plugin"
        release: "v001"
    spec:
      tolerations:
      - operator: "Exists"
      containers:
        - name: "ibmcloud-object-storage-plugin-container"
          image: "ibmcloud-object-storage-plugin:v001"
          imagePullPolicy: IfNotPresent
          args:
            - "-provisioner=ibm.io/ibmc-s3fs"
          env:
          - name: DEBUG_TRACE
            value: 'false'
      imagePullSecrets:
      - name: regcred
